create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  topic text not null default 'General conversation',
  listeners integer not null default 0 check (listeners >= 0),
  host text not null default 'You',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_name text not null default 'You',
  text text not null check (char_length(text) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.rooms enable row level security;
alter table public.messages enable row level security;

insert into public.rooms (name, topic, listeners, host)
select seed.name, seed.topic, seed.listeners, seed.host
from (values
  ('Tech Talk', 'AI, apps, coding & startups', 245, 'Alex'),
  ('Late Night', 'Relaxed conversations after dark', 198, 'Emma'),
  ('Music Vibes', 'Music, artists and good energy', 156, 'John')
) as seed(name, topic, listeners, host)
where not exists (select 1 from public.rooms);