create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  topic text not null default 'General conversation',
  listeners integer not null default 0 check (listeners >= 0),
  host text not null default 'You',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_name text not null default 'You',
  text text not null check (char_length(text) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.rooms enable row level security;
alter table public.messages enable row level security;